### ISSUE TITLE
An example of the different components in a web

### ISSUE THREAD

**Issue by angrykoala** [JuanjoSalvador/cakecss#1]
I would like to see cakecss in action

**Comment by JuanjoSalvador** [comment]
There is still a lot of work ahead, but you can see a preview on `test/index.html`

**Comment by angrykoala** [comment]
Then, just by creating a GH pages with that file would be enough!

**Comment by JuanjoSalvador** [comment]
Done!

http://juanjosalvador.me/cakecss/
