### ISSUE TITLE
Add a non minified version

### ISSUE THREAD

**Issue by EduFdezSoy** [JuanjoSalvador/cakecss#14]
Add a non minified version of the "final" or "compiled" .css file

**Comment by JuanjoSalvador** [comment]
Hmmm... OK, fine, why?

**Comment by EduFdezSoy** [comment]
This will make Cake more hackable for those who doesnt know Sass

**Comment by JuanjoSalvador** [comment]
Seems legit. OK! Feel free to make a PR!
