### ISSUE TITLE
Usinfg package.json scripts, you can avoid having a globally installed gulp

### ISSUE THREAD

**Issue by angrykoala** [JuanjoSalvador/cakecss#2]
For example:
```json
scripts:{
    "sass": "gulp sass"
}
```

Will allow using `npm run sass`, which will use the locally installed gulp (which already is a dev dependency) instead of needing gulp installed

**Comment by JuanjoSalvador** [comment]
Hey, cool idea.

**Comment by JuanjoSalvador** [comment]
Added command "build" on https://github.com/JuanjoSalvador/cakecss/commit/d3a3279220ca2e4cdb6a4f0f52b0b50f5f29a6a0

**Comment by angrykoala** [comment]
A command "build" may not be a good idea

`npm run build` will execute your program, however, `npm build` is a default command of npm, this can lead to confusion (in my experience)

**Comment by JuanjoSalvador** [comment]
Maybe `build-cake` would be better? Or `cook` 🍰 

Anyway, to run it you need to `npm run build`

**Comment by angrykoala** [comment]
+1 to `cook` :D
